<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Simple Calculator</title>
  <link rel="stylesheet" href="style.css">
  <style>
    body {
      font-family: Arial, sans-serif;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      background-color: #f0f0f0;
    }

    .calculator {
      width: 300px;
      border: 1px solid #ccc;
      border-radius: 10px;
      box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
      background-color: #fff;
    }

    #display {
      width: 93%;
      height: 50px;
      text-align: right;
      padding: 10px;
      font-size: 24px;
      border: none;
      border-bottom: 1px solid #ccc;
    }

    .buttons {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
    }

    button {
      width: 100%;
      height: 60px;
      font-size: 24px;
      border: none;
      background-color: #f9f9f9;
      cursor: pointer;
    }

    button:hover {
      background-color: #e0e0e0;
    }

    .clear {
      background-color: #ff6666;
      color: white;
    }

    .clear:hover {
      background-color: #ff3333;
    }
  </style>
</head>

<body>
  <div class="calculator">
    <input type="text" id="display" readonly>
    <div class="buttons">
      <button onclick="displayValue = displayValue + '7';   
        document.querySelector('#display').value = displayValue; ">7</button>
      <button onclick="displayValue = displayValue + '8';   
        document.querySelector('#display').value = displayValue; ">8</button>
      <button onclick="displayValue = displayValue + '9';   
        document.querySelector('#display').value = displayValue; ">9</button>
      <button onclick="displayValue = displayValue + '/';   
        document.querySelector('#display').value = displayValue; ">/</button>

      <button onclick="displayValue = displayValue + '4';   
        document.querySelector('#display').value = displayValue; ">4</button>
      <button onclick="displayValue = displayValue + '5';   
        document.querySelector('#display').value = displayValue; ">5</button>
      <button onclick="displayValue = displayValue + '6';   
        document.querySelector('#display').value = displayValue; ">6</button>
      <button onclick="displayValue = displayValue + '*';   
        document.querySelector('#display').value = displayValue; ">*</button>

      <button onclick="displayValue = displayValue + '1';   
        document.querySelector('#display').value = displayValue; ">1</button>
      <button onclick="displayValue = displayValue + '2';   
        document.querySelector('#display').value = displayValue; ">2</button>
      <button onclick="displayValue = displayValue + '3';   
        document.querySelector('#display').value = displayValue; ">3</button>
      <button onclick="displayValue = displayValue + '-';   
        document.querySelector('#display').value = displayValue; ">-</button>

      <button onclick="displayValue = displayValue + '0';   
        document.querySelector('#display').value = displayValue; ">0</button>
      <button onclick="displayValue = displayValue + '.';   
        document.querySelector('#display').value = displayValue; ">.</button>
      <button onclick="displayValue = eval(displayValue);   
        document.querySelector('#display').value = displayValue; ">=</button>
      <button onclick="displayValue = displayValue + '+';   
        document.querySelector('#display').value = displayValue; ">+</button>

      <button onclick="displayValue = '';
        document.querySelector('#display').value = displayValue">C</button>
    </div>
  </div>
  <script>
    let displayValue = '';
    document.querySelector('#display').value = displayValue;
  </script>
</body>

</html>
